import type {
  PartitionDraftRow,
  PartitionLayoutResult,
  PartitionLayoutRow,
  ValidationError,
} from "../types";
import { FLASH_OPTIONS_MB } from "../constants/flashOptions";

const SECTOR_SIZE = 0x1000;
const APP_ALIGNMENT = 0x10000;
const MAX_PARTITION_NAME_LENGTH = 15;
const NVS_MINIMUM_BYTES = 0x3000;
const DEFAULT_PARTITION_START_OFFSET = 0x10000;
const DEFAULT_TABLE_HEADER_COMMENT = "# Name,     Type, SubType, Offset,    Size,     Flags";
const GENERATED_COMMENT_PREFIX = "generated by esp partition toolbox for ";

function normalizeCommentLabel(line: string): string {
  return line
    .trim()
    .replace(/^#\s?/, "")
    .replace(/\s+/g, " ")
    .toLowerCase();
}

function isDefaultTableHeaderComment(line: string): boolean {
  return normalizeCommentLabel(line) === "name, type, subtype, offset, size, flags";
}

function isGeneratedFlashComment(line: string): boolean {
  return normalizeCommentLabel(line).startsWith(GENERATED_COMMENT_PREFIX);
}

function createRowId(): string {
  if (typeof crypto !== "undefined" && typeof crypto.randomUUID === "function") {
    return crypto.randomUUID();
  }

  return `row-${Math.random().toString(36).slice(2, 10)}`;
}

function alignUp(value: number, alignment: number): number {
  return Math.ceil(value / alignment) * alignment;
}

function parseNumericValue(value: string): number | null {
  const cleanedValue = value.trim().toUpperCase();

  if (!cleanedValue) {
    return null;
  }

  if (/^0X[0-9A-F]+$/.test(cleanedValue)) {
    return Number.parseInt(cleanedValue, 16);
  }

  const unitMatch = cleanedValue.match(/^(\d+)([KM])$/);
  if (unitMatch) {
    const baseValue = Number.parseInt(unitMatch[1], 10);
    const multiplier = unitMatch[2] === "M" ? 1024 * 1024 : 1024;
    return baseValue * multiplier;
  }

  if (/^\d+$/.test(cleanedValue)) {
    return Number.parseInt(cleanedValue, 10);
  }

  return null;
}

function normalizeTypeValue(value: string, fallback: string): string {
  const normalized = value.trim().toLowerCase();
  return normalized || fallback;
}

// ESP-IDF partition flags are colon-joined in the CSV's last column.
function composeFlags(encrypted: boolean, readonly: boolean): string {
  const flags: string[] = [];
  if (encrypted) flags.push("encrypted");
  if (readonly) flags.push("readonly");
  return flags.join(":");
}

export function normalizeSizeInput(value: string): string {
  const cleanedValue = value.trim().toUpperCase();

  if (/^0X[0-9A-F]+$/.test(cleanedValue)) {
    return cleanedValue;
  }

  const unitMatch = cleanedValue.match(/^(\d+)([KM])$/);
  if (unitMatch) {
    return `${Number.parseInt(unitMatch[1], 10)}${unitMatch[2]}`;
  }

  if (/^\d+$/.test(cleanedValue)) {
    return `${Number.parseInt(cleanedValue, 10)}`;
  }

  return cleanedValue;
}

export function parseSizeToBytes(value: string): number | null {
  return parseNumericValue(value);
}

/**
 * Infer the smallest standard flash size (MB) that fits an existing partition
 * table, by reading each partition row's literal offset + size (NOT the
 * re-packed layout). Offsets are parsed with the same grammar as sizes (hex,
 * decimal, or K/M suffix); a blank or unparseable offset auto-packs after the
 * previous row, so a malformed offset never silently drops the row's size from
 * the total (which would undercount the flash). Returns null when the content
 * has no usable rows, or when the table is larger than the biggest known flash
 * size. Used as a load-time fallback when the platform config declares no flash
 * size.
 */
export function inferFlashSizeMb(content: string): number | null {
  let cursor = DEFAULT_PARTITION_START_OFFSET;
  let maxEnd = 0;
  let sawRow = false;
  for (const rawLine of content.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const cells = line.split(",").map((c) => c.trim());
    if (cells.length < 5) continue;
    const sizeBytes = parseSizeToBytes(normalizeSizeInput(cells[4] ?? ""));
    if (sizeBytes == null || sizeBytes <= 0) continue; // skip rows whose size can't be parsed
    // Offset may be hex ("0x9000"), decimal, or K/M-suffixed. A blank or
    // unparseable offset auto-packs after the previous row so the row's size
    // still contributes to the total — inference can round up, never undercount.
    const parsedOffset = parseNumericValue(cells[3] ?? "");
    const offset = parsedOffset != null && parsedOffset >= 0 ? parsedOffset : cursor;
    const end = offset + sizeBytes;
    cursor = end;
    if (end > maxEnd) maxEnd = end;
    sawRow = true;
  }
  if (!sawRow || maxEnd <= 0) return null;
  const fit = FLASH_OPTIONS_MB.find((mb) => mb * 1024 * 1024 >= maxEnd);
  return fit ?? null;
}

export function formatHex(value: number): string {
  return `0x${value.toString(16).toUpperCase()}`;
}

export function formatBytes(value: number): string {
  if (value >= 1024 * 1024) {
    return `${(value / (1024 * 1024)).toFixed(2)} MB`;
  }

  if (value >= 1024) {
    return `${(value / 1024).toFixed(2)} KB`;
  }

  return `${value} B`;
}

export function formatSizeToPartitionUnit(bytes: number): string {
  if (bytes <= 0) return "0";

  if (bytes >= 1024 * 1024 && bytes % (1024 * 1024) === 0) {
    return `${bytes / (1024 * 1024)}M`;
  }

  if (bytes >= 1024 && bytes % 1024 === 0) {
    return `${bytes / 1024}K`;
  }

  return formatHex(bytes);
}

export type SizeUnit = "B" | "K" | "M";

export interface SizeComponents {
  value: number;
  unit: SizeUnit;
}

export function decomposeSize(sizeBytes: number): SizeComponents {
  if (sizeBytes <= 0) return { value: 0, unit: "K" };

  if (sizeBytes >= 1024 * 1024 && sizeBytes % (1024 * 1024) === 0) {
    return { value: sizeBytes / (1024 * 1024), unit: "M" };
  }

  if (sizeBytes % 1024 === 0) {
    return { value: sizeBytes / 1024, unit: "K" };
  }

  return { value: sizeBytes, unit: "B" };
}

/**
 * Parse a size string like "1536K", "2M", or "4096" into value and unit.
 * Preserves the user's chosen unit from the raw string (unlike decomposeSize).
 */
export function parseSizeString(sizeStr: string): SizeComponents {
  const trimmed = sizeStr.trim().toUpperCase();
  if (trimmed.endsWith("M")) {
    const num = Number(trimmed.slice(0, -1));
    return { value: Number.isFinite(num) && num >= 0 ? num : 0, unit: "M" };
  }
  if (trimmed.endsWith("K")) {
    const num = Number(trimmed.slice(0, -1));
    return { value: Number.isFinite(num) && num >= 0 ? num : 0, unit: "K" };
  }

  if (/^\d+$/.test(trimmed)) {
    return { value: Number.parseInt(trimmed, 10), unit: "B" };
  }

  const parsed = parseNumericValue(trimmed);
  if (parsed !== null && parsed >= 0) {
    return decomposeSize(parsed);
  }

  return { value: 0, unit: "K" };
}

export function composeSizeString(value: number, unit: SizeUnit): string {
  if (value <= 0) return "0";
  if (unit === "B") return String(value);
  return `${value}${unit}`;
}

const UNIT_MULTIPLIERS: Record<SizeUnit, number> = { B: 1, K: 1024, M: 1024 * 1024 };

export function convertSizeUnit(currentValue: number, fromUnit: SizeUnit, toUnit: SizeUnit): number {
  const bytes = currentValue * UNIT_MULTIPLIERS[fromUnit];
  const converted = bytes / UNIT_MULTIPLIERS[toUnit];
  return Math.max(1, Math.round(converted));
}

export function defaultRowsForFlashSize(flashSizeMb: number): PartitionDraftRow[] {
  const flashBytes = Math.max(flashSizeMb, 2) * 1024 * 1024;

  const nvsSize = 16 * 1024;
  const phySize = 4 * 1024;

  const nvsOffset = DEFAULT_PARTITION_START_OFFSET;
  const phyOffset = alignUp(nvsOffset + nvsSize, SECTOR_SIZE);
  const appOffset = alignUp(phyOffset + phySize, APP_ALIGNMENT);
  const appSize = Math.max(alignUp(flashBytes - appOffset, SECTOR_SIZE), SECTOR_SIZE);

  return [
    {
      id: createRowId(),
      name: "nvs",
      type: "data",
      subtype: "nvs",
      size: formatSizeToPartitionUnit(nvsSize),
      pinnedOffset: "",
      encrypted: false,
      readonly: false,
    },
    {
      id: createRowId(),
      name: "phy_init",
      type: "data",
      subtype: "phy",
      size: formatSizeToPartitionUnit(phySize),
      pinnedOffset: "",
      encrypted: false,
      readonly: false,
    },
    {
      id: createRowId(),
      name: "factory",
      type: "app",
      subtype: "factory",
      size: formatSizeToPartitionUnit(appSize),
      pinnedOffset: "",
      encrypted: false,
      readonly: false,
    },
  ];
}

export function parsePartitionCsv(content: string, fallbackFlashSizeMb = 8): {
  comments: string;
  rows: PartitionDraftRow[];
  errors: ValidationError[];
} {
  const rows: PartitionDraftRow[] = [];
  const commentLines: string[] = [];
  const errors: ValidationError[] = [];

  for (const [lineIndex, rawLine] of content.split(/\r?\n/).entries()) {
    const line = rawLine.trim();

    if (!line) {
      continue;
    }

    if (line.startsWith("#")) {
      if (isDefaultTableHeaderComment(line) || isGeneratedFlashComment(line)) {
        continue;
      }

      commentLines.push(line.replace(/^#\s?/, ""));
      continue;
    }

    const cells = line.split(",").map((cell) => cell.trim());
    if (cells.length < 5) {
      errors.push({ message: `Malformed CSV row at line ${lineIndex + 1}: expected at least 5 columns.`, severity: "warning" });
      continue;
    }

    const rawSize = cells[4] ?? "";
    const normalizedSize = normalizeSizeInput(rawSize);
    if (!parseSizeToBytes(normalizedSize)) {
      errors.push({ message: `Invalid partition size at line ${lineIndex + 1}: ${rawSize || "<empty>"}.`, severity: "blocking" });
    }

    const flags = cells[5] ?? "";

    rows.push({
      id: createRowId(),
      name: cells[0] || "partition",
      type: normalizeTypeValue(cells[1] || "data", "data"),
      subtype: normalizeTypeValue(cells[2] || "nvs", "nvs"),
      size: normalizedSize || "64K",
      // Offsets are re-packed on load; the user pins them manually in advanced mode.
      pinnedOffset: "",
      encrypted: /encrypted/i.test(flags),
      readonly: /readonly/i.test(flags),
    });
  }

  if (rows.length === 0) {
    errors.push({ message: "No usable partition rows found in CSV. Loaded default partition rows.", severity: "warning" });
  }

  return {
    comments: commentLines.join("\n"),
    rows: rows.length > 0 ? rows : defaultRowsForFlashSize(fallbackFlashSizeMb),
    errors,
  };
}

function resolvePartitionStartOffset(partitionOffset: string | number | undefined): number {
  let partitionTableOffset: number | null = null;

  if (typeof partitionOffset === "number" && Number.isFinite(partitionOffset)) {
    partitionTableOffset = partitionOffset;
  } else if (typeof partitionOffset === "string") {
    partitionTableOffset = parseNumericValue(partitionOffset);
  }

  if (partitionTableOffset == null || partitionTableOffset < 0) {
    return DEFAULT_PARTITION_START_OFFSET;
  }

  const minimumStart = alignUp(partitionTableOffset + SECTOR_SIZE, SECTOR_SIZE);
  return Math.max(DEFAULT_PARTITION_START_OFFSET, minimumStart);
}

export function calculateLayout(
  rows: PartitionDraftRow[],
  flashSizeMb: number,
  partitionOffset?: string | number,
): PartitionLayoutResult {
  const partitionStartOffset = resolvePartitionStartOffset(partitionOffset);
  const flashBytes = flashSizeMb * 1024 * 1024;
  const usable = Math.max(flashBytes - partitionStartOffset, 0);

  const errors: ValidationError[] = [];
  const layoutRows: PartitionLayoutRow[] = [];

  let cursor = partitionStartOffset;

  // Surface partition-table offset problems explicitly so a typo in the
  // Partition Start field doesn't get silently swallowed by the fallback.
  if (typeof partitionOffset === "string") {
    const raw = partitionOffset.trim();
    if (raw) {
      const parsed = parseNumericValue(raw);
      if (parsed == null) {
        errors.push({
          message: `Invalid partition table offset "${raw}" — using the default ${formatHex(DEFAULT_PARTITION_START_OFFSET)} instead.`,
          severity: "blocking",
        });
      } else if (parsed < 0) {
        errors.push({
          message: `Partition table offset cannot be negative — using the default ${formatHex(DEFAULT_PARTITION_START_OFFSET)} instead.`,
          severity: "blocking",
        });
      } else if (parsed % SECTOR_SIZE !== 0) {
        errors.push({
          message: `Partition table offset ${formatHex(parsed)} is not 4KB aligned — it will be up.`,
          severity: "warning",
        });
      }
    }
  }

  if (partitionStartOffset >= flashBytes) {
    errors.push({ message: "Partition start offset is outside the selected flash size.", severity: "blocking" });
  }

  for (const row of rows) {
    const rowType = normalizeTypeValue(row.type, "data");
    const alignment = rowType === "app" ? APP_ALIGNMENT : SECTOR_SIZE;

    // A pinned offset is used verbatim; otherwise the partition auto-packs
    // after the previous one. Pinned offsets are checked for overlap/alignment.
    const pinned = parseNumericValue(row.pinnedOffset ?? "");
    const isPinned = pinned != null && pinned >= 0;
    const offset = isPinned ? pinned : alignUp(cursor, alignment);

    if (isPinned && offset < cursor) {
      errors.push({
        message: `Partition ${row.name || "<unnamed>"} offset ${formatHex(offset)} overlaps earlier content — it must start at or after ${formatHex(cursor)}.`,
        severity: "blocking",
      });
    }

    if (isPinned && rowType !== "app" && offset % SECTOR_SIZE !== 0) {
      errors.push({
        message: `Partition ${row.name || "<unnamed>"} offset ${formatHex(offset)} is not 4KB aligned.`,
        severity: "blocking",
      });
    }

    const parsedSize = parseSizeToBytes(row.size);

    if (!parsedSize || parsedSize <= 0) {
      errors.push({ message: `Invalid size for partition ${row.name || "<unnamed>"}: ${row.size}`, severity: "blocking" });

      layoutRows.push({
        ...row,
        type: normalizeTypeValue(row.type, "data"),
        subtype: normalizeTypeValue(row.subtype, "nvs"),
        size: normalizeSizeInput(row.size),
        offset,
        end: offset,
        sizeBytes: 0,
        flags: composeFlags(row.encrypted, row.readonly),
      });

      continue;
    }

    const normalizedSize = alignUp(parsedSize, SECTOR_SIZE);
    if (normalizedSize !== parsedSize) {
      errors.push({
        message: `Size for partition ${row.name || "<unnamed>"} is not 4KB aligned. to ${formatHex(
          normalizedSize,
        )}.`,
        severity: "warning",
      });
    }

    const end = offset + normalizedSize;

    if (end > flashBytes) {
      errors.push({
        message: `Partition ${row.name || "<unnamed>"} exceeds flash boundary (${formatHex(end)} > ${formatHex(
          flashBytes,
        )}).`,
        severity: "blocking",
      });
    }

    layoutRows.push({
      ...row,
      type: normalizeTypeValue(row.type, "data"),
      subtype: normalizeTypeValue(row.subtype, "nvs"),
      size: normalizeSizeInput(row.size),
      offset,
      end,
      sizeBytes: normalizedSize,
      flags: composeFlags(row.encrypted, row.readonly),
    });

    cursor = end;
  }

  const allocated = layoutRows.reduce((sum, row) => sum + row.sizeBytes, 0);
  // Unallocated flash within the usable region — counts alignment gaps
  // between partitions, not just the space trailing the last partition.
  const free = Math.max(usable - allocated, 0);

  if (cursor > flashBytes) {
    errors.push({ message: "Allocated partition size exceeds available flash space.", severity: "blocking" });
  }

  validatePartitionRules(layoutRows, errors);

  return {
    rows: layoutRows,
    errors,
    allocated,
    free,
    usable,
    flashBytes,
    reservedBytes: partitionStartOffset,
  };
}

function validatePartitionRules(rows: PartitionLayoutRow[], errors: ValidationError[]): void {
  const nameCount = new Map<string, number>();
  const factoryRows: PartitionLayoutRow[] = [];
  const otaAppRows: PartitionLayoutRow[] = [];
  let hasOtaData = false;

  for (const row of rows) {
    const name = row.name.trim();
    const type = row.type.trim().toLowerCase();
    const subtype = row.subtype.trim().toLowerCase();

    if (!name) {
      errors.push({ message: `Partition name is required (row at offset ${formatHex(row.offset)}).`, severity: "blocking" });
    } else if (name.length > MAX_PARTITION_NAME_LENGTH) {
      errors.push({ message: `Partition name "${name}" exceeds ${MAX_PARTITION_NAME_LENGTH} characters.`, severity: "blocking" });
    }

    if (name) {
      nameCount.set(name, (nameCount.get(name) ?? 0) + 1);
    }

    if (type === "app" && row.sizeBytes > 0 && row.offset % APP_ALIGNMENT !== 0) {
      errors.push({
        message: `App partition "${name}" must be 64KB aligned (offset ${formatHex(row.offset)} is not).`,
        severity: "blocking",
      });
    }

    if (type === "app" && subtype === "factory") {
      factoryRows.push(row);
    }

    if (type === "app" && /^ota_\d+$/.test(subtype)) {
      otaAppRows.push(row);
    }

    if (type === "data" && subtype === "ota") {
      hasOtaData = true;
    }

    if (type === "data" && subtype === "nvs" && row.sizeBytes > 0 && row.sizeBytes < NVS_MINIMUM_BYTES) {
      errors.push({
        message: `NVS partition "${name}" is ${formatHex(row.sizeBytes)} — minimum recommended is 12KB (${formatHex(NVS_MINIMUM_BYTES)}).`,
        severity: "warning",
      });
    }

    // Read-only flag: data partitions only, never ota/coredump subtypes (ESP-IDF 5.2+).
    if (row.readonly) {
      if (type === "app") {
        errors.push({
          message: `Read-only flag is not allowed on app partition "${name}".`,
          severity: "blocking",
        });
      } else if (subtype === "ota" || subtype === "coredump") {
        errors.push({
          message: `Read-only flag is not allowed on the "${subtype}" subtype ("${name}").`,
          severity: "blocking",
        });
      }
    }

    // Custom (numeric) partition types must use the 0x40-0xFE user range.
    if (type !== "app" && type !== "data") {
      const numericType = parseNumericValue(type);
      if (numericType == null || numericType < 0x40 || numericType > 0xfe) {
        errors.push({
          message: `Custom type "${row.type}" for "${name}" must be a number in 0x40–0xFE.`,
          severity: "blocking",
        });
      }
    }
  }

  for (const [name, count] of nameCount) {
    if (count > 1) {
      errors.push({ message: `Duplicate partition name "${name}" (appears ${count} times).`, severity: "blocking" });
    }
  }

  if (factoryRows.length > 1) {
    errors.push({ message: `Only one factory app partition is allowed (found ${factoryRows.length}).`, severity: "blocking" });
  }

  if (otaAppRows.length > 0 && !hasOtaData) {
    errors.push({ message: "OTA app partitions require an otadata partition (data/ota).", severity: "blocking" });
  }

  if (otaAppRows.length > 1) {
    const sizes = new Set(otaAppRows.map((r) => r.sizeBytes));
    if (sizes.size > 1) {
      errors.push({ message: "All OTA app partitions should have the same size.", severity: "warning" });
    }
  }
}

/**
 * Largest size (bytes, 4 KB-aligned) the partition at `index` can take without
 * pushing a later partition past the flash boundary. It depends only on this
 * row's offset and the partitions after it — never on the row's own current
 * size — so a partition can always be grown back after it has been shrunk.
 */
export function maxSizeBytesForRow(
  rows: PartitionLayoutRow[],
  index: number,
  flashBytes: number,
): number {
  const row = rows[index];
  if (!row) {
    return SECTOR_SIZE;
  }

  // Walk the later partitions from the flash boundary backward, pinning each
  // to the latest offset it could legally occupy. What is left is the latest
  // offset this row may end at — and therefore its largest size.
  let latestEnd = flashBytes;
  for (let laterIndex = rows.length - 1; laterIndex > index; laterIndex -= 1) {
    const later = rows[laterIndex];
    const alignment = later.type.trim().toLowerCase() === "app" ? APP_ALIGNMENT : SECTOR_SIZE;
    latestEnd = Math.floor((latestEnd - later.sizeBytes) / alignment) * alignment;
  }

  return Math.max(latestEnd - row.offset, SECTOR_SIZE);
}

export function serializePartitionCsv(comments: string, rows: PartitionLayoutRow[]): string {
  return serializePartitionCsvForFlash(comments, rows, 8);
}

export function serializePartitionCsvForFlash(
  comments: string,
  rows: PartitionLayoutRow[],
  flashSizeMb: number,
): string {
  const output: string[] = [];

  output.push(`# Generated by ESP Partition Toolbox for ${flashSizeMb} MB flash`);

  if (comments.trim()) {
    for (const commentLine of comments.split(/\r?\n/)) {
      const line = commentLine.trim();
      if (isDefaultTableHeaderComment(line) || isGeneratedFlashComment(line)) {
        continue;
      }

      output.push(line ? `# ${line}` : "#");
    }
  }

  output.push(DEFAULT_TABLE_HEADER_COMMENT);

  for (const row of rows) {
    output.push(
      [
        row.name,
        row.type,
        row.subtype,
        formatHex(row.offset),
        row.size,
        row.flags,
      ]
        .map((cell) => cell || "")
        .join(", "),
    );
  }

  return `${output.join("\n")}\n`;
}

export function createEmptyRow(): PartitionDraftRow {
  return {
    id: createRowId(),
    name: "partition",
    type: "data",
    subtype: "spiffs",
    size: "64K",
    pinnedOffset: "",
    encrypted: false,
    readonly: false,
  };
}
